---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-k8s-svcacc
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-k8s-svcacc
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-k8s-svcacc
subjects:
- kind: ServiceAccount
  name: app-k8s-svcacc
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
